module.exports = {
  apps: [
    {
      name: "lets-todo-api-prod",
      script: "./server.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env_file: "config/env/.env.production",
      log_file: "./logs/prod-combined.log",
      out_file: "./logs/prod-out.log",
      error_file: "./logs/prod-error.log",
      time: true,
    },
    {
      name: "lets-todo-api-feat",
      script: "./server.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: true,
      max_memory_restart: "1G",
      env_file: "config/env/.env.feature",
      log_file: "./logs/feat-combined.log",
      out_file: "./logs/feat-out.log",
      error_file: "./logs/feat-error.log",
      time: true,
    },
    {
      name: "lets-todo-api-stage",
      script: "./server.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env_file: "config/env/.env.staging",
      log_file: "./logs/stage-combined.log",
      out_file: "./logs/stage-out.log",
      error_file: "./logs/stage-error.log",
      time: true,
    },
  ],
};
